routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Use Illuminate\Support\Facades\Input;
Use App\Edital;
Use App\Agenda;


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

//INSERÇÃO/DELEÇÃO DE POSTS
Route::post('/home/add', 'FeedControle@create')->name('CriarFeed');
Route::get('/home/apagar/{id}', 'FeedControle@destroy')->name('ApagarFeed');

Route::resource('startup', 'StartupController');
//PALAVRA DO GESTOR
Route::get('/home/PalavraG', 'PalavraGController@store')->name('AdicionarP');
Route::get('/home/apaga/{id}', 'PalavraGController@destroy')->name('ApagarP');

Route::get('/Reset', function(){return view('auth.trocarSenha');})->name("nova");

Route::get('Comunidade', 'mentoresControle@index');

Route::get('/tabelaMentor/{id}', 'mentoresControle@show')->name('ativar');
Route::get('Mentores', function () {return view('Mentores');});

//INSERÇÃO DE DADOS PESSOAIS
Route::get('/Perfil', 'UserController@perfil')->name("perfil");
Route::post('/Perfil/dadosPessoais', 'UserController@updateFoto')->name("adc");

//Rotas para a página de editais
Route::get('/ShowEdital', 'EditalController@index')->name('show');
Route::get('/DetailEdital/{id}', 'EditalController@detailEdital');
Route::post('/ShowEdital', function(){
    $q = Input::get('search');
    if($q != ''){
        $edital = Edital::where('titulo', 'LIKE' ,'%'.$q.'%')->get();
        if(count($edital) >= 1 ){
            return view('edital.index', compact('edital'));
        }
    }
    return back();
});

//EDITAIS
Route::post('/Create', 'EditalController@inserir')->name('createEdital');
Route::post('/Update/{id}', 'EditalController@update')->name('updateEdital');
Route::get('/RemoveEdital/{id}', 'EditalController@remove');

//BLOG
Route::get('/Blog', 'BlogController@index')->name('Blog');
Route::post('Blog/add', 'BlogController@store')->name('criarBlog'); //criando dados do blog
Route::get('/deleteBlog/{id}', 'BlogController@destroy'); //ecluir dados do Blog
Route::get('/edita/{id}', 'BlogController@edit'); //direcionado para rota
Route::get('/editar/{id}', 'BlogController@update')->name("editar"); //editanoo os dados
Route::post('/Showblog', 'BlogController@show');

//AGENDA'
Route::get('/Agenda', 'AgendaController@index')->name('agendaShow');
Route::get('/AdicionarEvento', 'AgendaController@insert');
Route::post('/AtualizarEvento/{id}', 'AgendaController@update')->name('AtualizarEvento');
Route::get('/RemoverEvento/{id}', 'AgendaController@remove');
Route::post('/Agenda', function(){
    $q = Input::get('searchAgenda');
    if($q != ' '){
        $agenda = Agenda::where('titulo','LIKE' ,'%'.$q.'%')
                        ->orWhere('evento','LIKE' ,'%'.$q.'%')
                        ->orWhere('mentor','LIKE' ,'%'.$q.'%')
                        ->orWhere('local','LIKE' ,'%'.$q.'%')
                        ->orWhere('descricao','LIKE' ,'%'.$q.'%')
                        ->orWhere('equipamento','LIKE' ,'%'.$q.'%')->get();
        if(count($agenda) >= 1 ){
            return view('agenda.index', compact('agenda'));
        }
    }
    $agenda = Agenda::all();
    return view('agenda.index', compact('agenda'));
});

app/Startup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Startup extends Model
{
    protected $fillable = ['id','nome','email','senha','ativo','nivel'];

    public function getId(){return $this->id;}
    public function getNome(){return $this->nome;}
    public function getEmail(){return $this->email;}
    public function getSenha(){return $this->senha;}
    public function getAtivo(){return $this->ativo;}
    public function getNivel(){return $this->nivel;}
}

app/Http/Controllers/StartupController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Login;
use Illuminate\Support\Facades\Hash;
use App\Rules\Uppercase;
use Illuminate\Http\Request;

class StartupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $startups = User::latest()->paginate(5);
        return view('startup.index', compact('startups'))
                ->with('i', (request()->input('page', 1)-1)*5);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('startup.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max: 20',
            'email' => 'required|email',
            'password' => 'required'//Depois colocar o new Uppercase aqui
        ]);
        //dd($request->all());
        
        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'nivel' => $request->nivel,
        ]);
            return redirect()->route('startup.index')
                    ->with('success', 'Nova startup adicionada!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $startup = Startup::find($id);
        if($startup->ativo == 0)
        {
            $startup->ativo = 1;
        }
        else
        {
            $startup->ativo = 0;
        }
        $startup->save();
        return redirect()->back();
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/startup/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Registro de novo usuário') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('startup.store') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="nome" class="col-md-4 col-form-label text-md-right">{{ __('Nome') }}</label>

                            <div class="col-md-6">
                                <input id="nome" type="text" class="form-control{{ $errors->has('nome') ? ' is-invalid' : '' }}" name="name" value="{{ old('nome') }}" required autofocus>

                                @if ($errors->has('nome'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('nome') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Senha') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirmação de senha') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Mentor ou Startup:') }}</label>

                            <div class="col-md-6">
                                <select class="form-control" name="nivel" required>
                                    <option selected disabled>Selecione qual o tipo de usuário</option>
                                    <option value="1">Startup</option>
                                    <option value="2">Mentor</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Registrar') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/startup/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  @auth
    @if(\Auth::User()->nivel==0)
    <div style='margin-bottom: 30px;' class="col-md-12">
        <a style='position: relative; float: right;' href="{{route('startup.create')}}" class="btn btn-sm btn-success">Adicionar Startup/Mentor</a>
    </div>
    @endif
  @endauth
  
    <div class='rows'>
        <table class="table table-hover table-bordered">
            <thead class='thead'>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nome</th>
                  <th scope="col">E-mail</th>
                  <th scope="col">senha</th>
                  <th scope='col'>Ativo</th>
                </tr>
            </thead>
            @foreach ($startups as $startup)
              <tr>
                <td>{{++$i}}</td>
                <td>{{$startup->nome}}</td>
                <td>{{$startup->email}}</td>
                <td>{{$startup->senha}}</td>
                <td>
                  @if($startup->ativo)
                    <a class="btn btn-sm btn-danger" href="{{route('startup.show', $startup->id)}}">Inativo</a>
                  @else
                    <a class="btn btn-sm btn-success" href="{{route('startup.show', $startup->id)}}">Ativo</a>
                  @endif
                </td>
              </tr>
            @endforeach
    </table>
    </div>

    {!! $startups->links() !!}
    <div class="col-md-12">
        <a href="{{url('/home')}}" class="btn btn-sm btn-success">Voltar Home</a>
    </div>
</div>
@endsection